### ISSUE TITLE
Doesn't show the temperature and clock speed for Ryzen

### ISSUE THREAD

**Issue by atkars** [ArcadeRenegade/SidebarDiagnostics#187]
**1. Your Operating System**
Windows 10
**2. App Version**
3.4.6
**3. Any Relevant Settings**
None
**4. Steps to Reproduce**
None

**Comment by meep26** [comment]
Does this issue resolved? mine too

**Comment by JimmyCushnie** [comment]
This issue is not yet resolved.

**Comment by ArcadeRenegade** [comment]
I don't have a Ryzen. Could someone please download the latest version of Open Hardware Monitor and see if it works there? If so I will update my repo to use the latest version of OHM.

**Comment by JimmyCushnie** [comment]
The latest version of OHM does not work with Ryzen, but there is an open PR to support it. https://github.com/openhardwaremonitor/openhardwaremonitor/pull/970

**Comment by ArcadeRenegade** [comment]
OK I'll fork it. Thanks.

**Comment by JimmyCushnie** [comment]
More info after some quick research:

[LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) is a more active fork of OHM that supports Ryzen. Perhaps Sidebar Diagnostics should move to that.

**Comment by ArcadeRenegade** [comment]
People are reporting inaccurate Ryzen temps due to the changes in that pull request. Still think I should merge it? 🤔

**Comment by ArcadeRenegade** [comment]
I'll give LibreHardwareMonitor a try. I'll upload an exe for you to try after I compile it. If it works then I'll do a release.

**Comment by cjmitsuki** [comment]
You should speak with Mumak, the dev for HwInfo64.  He had some problems with conflicting monitors and worked with Frank (CPU-Z) to fix the issue and he may be able to point you toward other solutions and ways to monitor Ryzen.  Also Ray, dev for SIV (System Information Viewer) is also very knowledgeable and they are all very involved and helpful to others.  Mumak (Martin) is involved on his [Forum](https://www.hwinfo.com/forum/) as well as Ray being reachable on his [SITE](http://rh-software.com/) and [FORUM](https://siv.boards.net/).  They also frequent [Overclock.net](https://www.overclock.net/).  They are always helpful and dont mind sharing knowledge in this area.

**Comment by ArcadeRenegade** [comment]
[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3027267/Debug.zip)

Hey guys, here is a build with LibreHardwareMonitor. Could you please try it with your Ryzen and see if it works? Thanks.

**Comment by atkars** [comment]
Will try after work and edit this post afterwards. Thank you!

**Comment by JimmyCushnie** [comment]
It works with my Ryzen 7 2700X, but the reported temperature is consistently exactly 10 degrees celsius higher than the actual temperature.

**Comment by cjmitsuki** [comment]
If the temp is exactly 10c off then that is due to it monitoring the Tctl temp and not the Tdie temp which is the true temp of the hottest core of the die.  AMD purposely added an offset to the Tctl monitor for cooling purposes but it wasn’t needed imo.  The software should follow the Tdie temp for accuracy imo.

**Comment by ArcadeRenegade** [comment]
HWInfo64 SDK is not free, unfortunately.

https://www.hwinfo.com/sdk/

**Comment by ArcadeRenegade** [comment]
It was one of the options that I looked at when I first wrote the Sidebar but the pricing model pushed me to Open Hardware Monitor.

**Comment by ArcadeRenegade** [comment]
Creator of hwinfo got back to me. They have a free licensing model but it's shared memory and requires running hwinfo.exe in parallel with my sidebar. Not an ideal option for most users.

**Comment by cjmitsuki** [comment]
Yeah, I figured that would be the case.  It’s how any of the external
software communicated to HwInfo64.  I know there are DLL files that some
software like MSI afterburner and Aida64 use to pull in data from HwInfo64
without it actually running but I’m not sure how you could use that to the
benefit of the sidebar.  The .dll files should be able to be easily
extracted from MSI afterburners install exe.

**Comment by ArcadeRenegade** [comment]
MSI Afterburner and Aida64 are able to use HWInfo without running the HWInfo.exe because they pay for HWInfo's enterprise pricing model. Unfortunately, since this is free open source software, that is not possible. I reached out to the creator of HWInfo about getting it for free since this is open source software but they said they only offer the DLL which requires running HWInfo.exe.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/ has gotten a lot of activity recently. I don't have a Ryzen so could you please run their build and see if it works with Ryzen for me?

Thanks,
https://ci.appveyor.com/project/LibreHardwareMonitor/librehardwaremonitor/build/artifacts

**Comment by thomascooper** [comment]
Can you give me steps to test your software with LibreHardwareMonitor? I'll happily test it out.

**Comment by andycjw** [comment]
@ArcadeRenegade I tested the latest build of LibreHardwareMonitor, it is working with the latest Ryzen, and all the data, including temperature, clocks, voltage and wattage are showing correctly

**Comment by cjmitsuki** [comment]
Which voltages are showing?  VDDG isnt showing with any software Ive seen so far besides Ryzen Master.  Many would love to be able to monitor that voltage since it is critical with higher memory frequencies such as 3800cl14.  Not sure if AMD has that voltage locked out from monitors or not though.

**Comment by andycjw** [comment]
is it shown as SVI2, it's probably vcore for the cpu

**Comment by cjmitsuki** [comment]
Svi2 isnt a voltage but a category of voltages containing vCore, SoC, and other various voltages.  Its one of the more accurate monitors.  It closely resembles the voltages coming straight from the VRM after LLC adjusts the voltae before it is fed to the destination.  At least on my C7H it is this way.  There is a forum thread by The Stilt on overclock.net which contains various bits of information on Matisse.  Its called “Strictly Matisse” he also has other threads on Ryzen behavior there as he is regarded as one of the Ryzen authorities in the AMD community.

**Comment by ArcadeRenegade** [comment]
I'll create a build of the program with Libre Hardware Monitor and post it here for you guys to try out

**Comment by pgsill** [comment]
Fantastic, thanks!

**Comment by pgsill** [comment]
@ArcadeRenegade sorry to ping you, but any chance you've made any progress on it or have an ETA? If not, no problem! Just curious. Thanks a bunch!

**Comment by ArcadeRenegade** [comment]
Hey guys sorry this is late but here is a **debug** build of Sidebar Diagnostics using the latest version of LibreHardwareMonitor. 

Please unzip then run SidebarDiagnostics.exe

If this fixes your Ryzen issues then I will do a proper release with the new version.

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3464503/Debug.zip)

**Comment by rdd462** [comment]
Works for my Ryzen 7 2700x

**Comment by ArcadeRenegade** [comment]
Thank you! Could anyone else with a Ryzen please confirm?

**Comment by shadeyg56** [comment]
Temp works on my Ryzen 3 2200G however clock speed still doesn't work. I don't know if this is related to Ryzen but for RAM, voltage and speed don't work either (on the release version or the debug version you've provided)

**Comment by klandingball** [comment]
On Ryzen 3600 - volt, temp, load are working.

No clock or fan speed info.

thanks for your work :)

**Comment by mbtuchman** [comment]
Works for me.

**Comment by thomascooper** [comment]
Working with my Ryzen 5 3600!

**Comment by carlalldis** [comment]
Working with 3900x

**Comment by ArcadeRenegade** [comment]
Sounds like it's working then. I will do a proper release.

**Comment by BL0o** [comment]
It updated today to last version 3.5.3 and now my cpu temp is wrong. it floats around 59-60°c and for a moment i saw -47°c. But the real temp with "Sense Mi Skew" option disabled in bios is 30-33°c in idle. 
![firefox_2019-08-27_15-15-04](https://user-images.githubusercontent.com/54583271/63770716-6daf2300-c8de-11e9-81ad-5cb021bf11ad.jpg)
Sense Mi Skew is explained here https://www.techporn.ph/amd-clarifies-ryzen-7-1800x-1700x-temperature-readings/ idk why they did it this way and added that offset but maybe the wrong readings are somehow related to this stuff?
(tho' the previous version was showing the cpu temp correctly!)

**Comment by BL0o** [comment]
Yup, it did not show the clock in 3.5.2 and it doesn't in 3.5.3 but i do not mind. 
This is what it shows with all boxes checked under Cpu metrics tab and "show all core clocks"
![SidebarDiagnostics_2019-08-27_21-50-50](https://user-images.githubusercontent.com/54583271/63799553-f8ab1000-c914-11e9-8151-c90091e653b4.jpg)
Hmm maybe the offset option will help but i find weird for Amd to set on offset of 27°c instead of 20 or 30. 
![SidebarDiagnostics_2019-08-27_21-56-58](https://user-images.githubusercontent.com/54583271/63799914-b930f380-c915-11e9-9264-f7cfa830f142.jpg)
Oh and i forgot to mention when i installed version 3.5.2 i got that performance counter error and i tried to rebuild the counters with lodctr /R so i'm thinking maybe there are some problems on my end and this is why it doesn't work, i should do a clean win10 install and report back.

**Comment by ArcadeRenegade** [comment]
We found a fix for the Ryzen temperature issue.

Attached is a DEBUG build.
Could you please download this zip, unzip, and run SidebarDiagnostics.exe? If your Ryzen CPU temperature looks with that build, then I will do a proper release.

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3934490/Debug.zip)

**Comment by RodrigoRVieira** [comment]
Just tried this Debug package and it matches the HwInfo64's Tctl/Tdie sensor but I'm new to this platform... I believe (hope) that the real temperature is the lowest one (Tdie) that matches Ryzen Master.

![RyzenMasterHwInfo64Sidebar](https://user-images.githubusercontent.com/7377236/70367361-fba38e00-187d-11ea-90ad-77542dd46570.PNG)

**Comment by ArcadeRenegade** [comment]
Looks like it's still not getting the right temperature I think.

Could you please run LibreHardwareMonitor and take a screenshot of the CPU temp sensor names? 

It should look like this:

![image](https://user-images.githubusercontent.com/13874898/70367458-00a01780-1855-11ea-88e4-d56cc1115fd3.png)

https://ci.appveyor.com/api/buildjobs/vqy8dj2o2ldn416k/artifacts/bin%2FRelease.zip

**Comment by RodrigoRVieira** [comment]
Here it is.

![RyzenMasterLibreSidebar](https://user-images.githubusercontent.com/7377236/70367527-8c2e9e00-187f-11ea-8df4-0d7e974ba736.PNG)

**Comment by ArcadeRenegade** [comment]
That's odd... The temps are the same. Mind if I post your screens in this other thread so the Libre devs can see it?

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/167

**Comment by RodrigoRVieira** [comment]
Sure, go ahead. They are both displaying same temps all the time.

**Comment by RodrigoRVieira** [comment]
Just found this in the thread you shared above:

@TheRadziu
T_ctl and T_die are equal on your screenshot, which **should be correct for the 3800X**.

**Comment by ArcadeRenegade** [comment]
I see. Well in the debug build I'm getting the Tdie now instead of the Tctl so it should fix the issue for other Ryzen users but it looks like for your CPU since both temps are the same it won't have any effect.

**Comment by RodrigoRVieira** [comment]
I'll just consider it ~10C less than real temperature... but that weird fluctuation is annoying though.

Btw, thank you for this tool :)

**Comment by SubElement** [comment]
> 
> 
> We found a fix for the Ryzen temperature issue.
> 
> Attached is a DEBUG build.
> Could you please download this zip, unzip, and run SidebarDiagnostics.exe? If your Ryzen CPU temperature looks with that build, then I will do a proper release.
> 
> [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3934490/Debug.zip)

Is this meant to fix the clock speed issue too? I'm using a Ryzen 3700X and can not see my clock speed using either release or this debug build.

**Comment by ArcadeRenegade** [comment]
Sorry I didn't update LibreHardwareMonitor before building that. This should have the latest version.

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3991269/Debug.zip)

**Comment by SubElement** [comment]
> 
> 
> Sorry I didn't update LibreHardwareMonitor before building that. This should have the latest version.
> 
> [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3991269/Debug.zip)

Fast reply, thank you!

But, looks like it's still not working even in that build. It also seems to trash when I toggle Clock On or Off on the CPU and try and apply.

**Comment by attempted** [comment]
Same issue with a 3950x and that build.

**Comment by panryba13** [comment]
For Ryzen 3600X the sidebar only shows me the wrong voltage (constant 1.07v - 1.08v), load and temperature (quite correctly). Does not display clock frequency. I'm using the latest version 3.5.3

**Comment by ArcadeRenegade** [comment]
Hey everyone I released version 3.5.4.

I broke the auto updater in the last version so you will probably have to uninstall and install 3.5.4.
Sorry about that.

The auto updater should work from now on hopefully.

**Comment by SubElement** [comment]
> Hey everyone I released version 3.5.4.
> 
> I broke the auto updater in the last version so you will probably have to uninstall and install 3.5.4.
> Sorry about that.
> 
> The auto updater should work from now on hopefully.

Thanks man!

I see that Clock Speed still isn’t working. Any chance on a fix for that?

**Comment by ArcadeRenegade** [comment]
Can you please show me a screenshot of your click spreed in LibreHardwareMonitor?

**Comment by SubElement** [comment]
> 
> 
> Can you please show me a screenshot of your clock spreed in LibreHardwareMonitor?

Sure thing!

![LibreHardwareMonitor_VadPs8KZsM](https://user-images.githubusercontent.com/7236925/78060719-9b050780-73be-11ea-887d-3b7cba18433f.png)

**Comment by ArcadeRenegade** [comment]
[Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4411432/Release.zip)

Could you please try it with this build and let me know if it works?

**Comment by SubElement** [comment]
> 
> 
> [Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4411432/Release.zip)
> 
> Could you please try it with this build and let me know if it works?

Yes it does! Thanks!

It does pop up with an error about updating though, and how auto-update is now disabled.

**Comment by JimmyCushnie** [comment]
It's working for me as well :D

**Comment by JPetovello** [comment]
> 
> 
> [Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4411432/Release.zip)
> 
> Could you please try it with this build and let me know if it works?

Working here too!

**Comment by cormac85** [comment]
Still not showing clock speed here for win10, Ryzen5 2600, ASUS TUF Gaming X-570-Plus:

![image](https://user-images.githubusercontent.com/9368638/78268192-bfb4c880-74ff-11ea-974b-83318f818728.png)

**Comment by ArcadeRenegade** [comment]
Released 3.5.5

@cormac85 please upgrade and try again

**Comment by cormac85** [comment]
> 
> 
> Released 3.5.5
> 
> @cormac85 please upgrade and try again

Wow, that was fast! Well done man, works a charm 💯 
![image](https://user-images.githubusercontent.com/9368638/78306812-366fb700-753c-11ea-9e8d-8ecbc6afd050.png)

**Comment by RodrigoRVieira** [comment]
Working fine, thanks! :)

![image](https://user-images.githubusercontent.com/7377236/78313108-29e36280-752c-11ea-84ee-5385a08f4a65.png)

**Comment by ArcadeRenegade** [comment]
👍 👍

**Comment by schiffy91** [comment]
![disparity](https://user-images.githubusercontent.com/2189541/81643676-ea395180-93da-11ea-91b4-48a8f968623e.png)

I'm still seeing a disparity between what Ryzen Master reports and what Sidebar Diagnostics reports. So, I downloaded Libre Hardware Monitor and examined what's going on. It looks like Sidebar Diagnostics is reporting Core Tctl, but, if IIUC, Ryzen Master reports CCDs Max (Tdie) -- but averaged over a few polls. I don't think we ought to do any sort of signal averaging, but it'd be useful to report the "canonical" value (i.e. CCDs Max) instead.

@ArcadeRenegade LMK if you'd like any help.

**Comment by schiffy91** [comment]
It looks like we'd want to change the following line of code. It'd probably be useful to not have a hacky check for Ryzen. @ArcadeRenegade LMK if you have any suggestions.
`
                    _tempSensor =
                        _hardware.Sensors.Where(s => s.SensorType == SensorType.Temperature && (s.Name == "CPU Package" || s.Name.Contains("Tdie"))).FirstOrDefault() ??
                        _hardware.Sensors.Where(s => s.SensorType == SensorType.Temperature).FirstOrDefault();
                `

**Comment by ArcadeRenegade** [comment]
Sounds good could you please make a pull request? Thx
