### ISSUE TITLE
AMD 3950x only shows 8 cores instead of 16 for clock. 

### ISSUE THREAD

**Issue by APOPHIS9283** [ArcadeRenegade/SidebarDiagnostics#288]
I am an android developer, never done anything with Windows though. If I can help let me know. Maybe point me in the right direction lol.

**1. Your Operating System**
Windows 10 pro

**2. App Version**
latest

**3. Any Relevant Settings**
CPU

**4. Steps to Reproduce**
Enable CPU

**Comment by ArcadeRenegade** [comment]
Can you please run LibreHardwareMonitor and take a screenshot of your our
cpu metrics in it?

**Comment by APOPHIS9283** [comment]
[LibreHardwareMonitor.Report.txt](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4467831/LibreHardwareMonitor.Report.txt)

**Comment by APOPHIS9283** [comment]
Also Ive checked every location, I know of. They all show that it is 16-core/32 thread

**Comment by HellfireXD** [comment]
I have the same issue with my 3950X.

![3950x](https://user-images.githubusercontent.com/7536673/98449537-60a4db00-2102-11eb-9d91-3e6ec20fef0e.png)

**Comment by ThisOneIsForPosting** [comment]
Same.  Running version v3.5.6 and my Ryzen 3900X is only showing 8 cores

**Comment by ArcadeRenegade** [comment]
Can you run the latest version of LibreHardwareMonitor and see if it happens there.

**Comment by ThisOneIsForPosting** [comment]
![Screenshot 2020-11-16 144600](https://user-images.githubusercontent.com/61810625/99300390-87f25b00-281a-11eb-9bbc-6579ae1a21b0.jpg)

**Comment by ArcadeRenegade** [comment]
Thx. Looks like LibreHardwareMonitor is only finding 12 clock speeds for some reason

**Comment by ArcadeRenegade** [comment]
Could you please try this build and let me know if it works?

[Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/5549718/Release.zip)

**Comment by ThisOneIsForPosting** [comment]
I've run the release you provided but unfortunately, I'm still seeing the same problem as the newer release.

![Capture](https://user-images.githubusercontent.com/61810625/99736112-d9f1e580-2a93-11eb-88bf-82c42d6cfbbf.JPG)

**Comment by HellfireXD** [comment]
Same for me as well, the issue persists.

![image](https://user-images.githubusercontent.com/7536673/100900307-b619a100-3490-11eb-9d37-7054807a06bc.png)

**Comment by HellfireXD** [comment]
LibreHardwareMonitor 0.8.6 seams to have this fixed. 
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases

![image](https://user-images.githubusercontent.com/7536673/100900660-0ee93980-3491-11eb-9c43-28ca8bd06917.png)

**Comment by ThisOneIsForPosting** [comment]
Great!  How can do I update only the LibreHardwareMonitor 0.8.6 portion of SidebarDiagnostics installation?  Thanks

**Comment by ArcadeRenegade** [comment]
Could you please try with this build?

[Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/5638563/Release.zip)

**Comment by ThisOneIsForPosting** [comment]
Thanks @ArcadeRenegade.  I've removed v.3.5.6 and installed only the release you provided and unfortunately, there was no difference (screenshot attached).
![Screenshot](https://user-images.githubusercontent.com/61810625/101086681-374f6180-357f-11eb-8737-b5445a7f021d.jpg)

**Comment by ArcadeRenegade** [comment]
The zip I uploaded above is not a release, it is just a compiled version of the program w/ the new commits from LibreHardwareMonitor. It doesn't have an installer, just need to extract the zip and run SidebarDiagnostics.exe

**Comment by ThisOneIsForPosting** [comment]
Right, sorry if my message was confusing. I uninstalled the previous version so it didn't interfere with your updated version. I then unzipped your updated version and ran it in order to see if there was a change, unfortunately it still has the same problem. Unless I'm missing a step or something else on my end?  I appreciate you following up and trying to fix this.

> The zip I uploaded above is not a release, it is just a compiled version of the program w/ the new commits from LibreHardwareMonitor. It doesn't have an installer, just need to extract the zip and run SidebarDiagnostics.exe

**Comment by ArcadeRenegade** [comment]
I just released version 3.5.7 could you please update?

**Comment by ThisOneIsForPosting** [comment]
I've updated it to 3.5.7, thank you.  Unfortunately, I still have the same issue, I can only see 9 of
![2020 12 08 Screenshot](https://user-images.githubusercontent.com/61810625/101555395-9863a480-3986-11eb-8f3d-70d2759f8960.jpg)
 12 cores for my 3900X. I've attached a screenshot.

**Comment by ArcadeRenegade** [comment]
Does LibreHardwareMonitor not show all your cores?

**Comment by ThisOneIsForPosting** [comment]
Hi @ArcadeRenegade, 
I ran the latest version of LibreHardwareMonitor and yes it does show all of my cores under the CLOCKS category. I've attached a screenshot for reference.

![Screenshot 2020-12-09 141329](https://user-images.githubusercontent.com/61810625/101678879-8f2d1300-3a2c-11eb-8b81-7bf366c4151c.jpg)

**Comment by ArcadeRenegade** [comment]
It was a silly regex bug... Could you please unzip this and run SidebarDiagnostics.exe and let me know if it is fixed? Thanks.

[Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/5669602/Release.zip)

**Comment by ThisOneIsForPosting** [comment]
Well @ArcadeRenegade, I have downloaded your file, unzipped it, and ran SidebarDiagnostics.exe and all I can say is............................. IT'S FIXED!!!   :) 
Thank you for all your hard work!

![fixed](https://user-images.githubusercontent.com/61810625/101713346-79880f80-3a65-11eb-8f0b-32eb2987f2de.jpg)

**Comment by HellfireXD** [comment]
The release works for me as well on my 3950X.
I have it unpacked in the directory as 3.5.8 instead of overwriting the 3.5.7 directory.

![image](https://user-images.githubusercontent.com/7536673/101780860-175ef700-3ac5-11eb-91b4-a4b7db0ffaf2.png)

**Comment by ArcadeRenegade** [comment]
It's not a release. Just a test. I'll publish a release today.
