### ISSUE TITLE
Cannot see CPU temperature

### ISSUE THREAD

**Issue by LiverBlow** [ArcadeRenegade/SidebarDiagnostics#334]
**1. Is this a feature request?**

No

**2. Your Operating System**

Windows 10 Pro

**3. App Version**
3.5.6

**4. Any Relevant Settings**
Not that I know of, I havent configured anything specially. This is a relatively new windows installation too. I can see the temp in Ryzen Master. 

**5. Steps to Reproduce**

Install and open. If there is anything else I can try please let me know.

**Comment by LiverBlow** [comment]
![image](https://user-images.githubusercontent.com/6471972/101512880-6f85e400-3973-11eb-84b6-f4f7c4022524.png)

**Comment by LiverBlow** [comment]
I have selected the CPU temp option in the settings:

![image](https://user-images.githubusercontent.com/6471972/101513205-d3101180-3973-11eb-92f2-60873d11b73b.png)

**Comment by ArcadeRenegade** [comment]
There will be an update soon that should fix this

**Comment by LiverBlow** [comment]
Awesome thank you. Can you also check if fan speeds are being recognised
correctly, I think that's also acting up.

**Comment by ArcadeRenegade** [comment]
I can only show whatever data LibreHardwareMonitor can pull so I would
check with them first.

**Comment by LiverBlow** [comment]
Ah ok I didn't know that so will check it out. Thank you for the awesome
app btw.

**Comment by LiverBlow** [comment]
Ok looking at the latest build of LibreHardwareMonitor I see this 👍 
![image](https://user-images.githubusercontent.com/6471972/101542749-26e22100-399b-11eb-8afb-6ef0dfb15d88.png)

**Comment by ArcadeRenegade** [comment]
I just released version 3.5.7 could you please update?

**Comment by LiverBlow** [comment]
Working now thank you, however Fan speed is still not appearing  despite being present in Libre, shall I create a seperate bug for this?

**Comment by ArcadeRenegade** [comment]
The fans are from the mobo but libre doesn't say which one is a CPU fan. I don't have a consistent way of pulling it.

**Comment by LiverBlow** [comment]
Ah ok not to worry not as important as temps! Thanks again 👍
