### ISSUE TITLE
SystemIO error

### ISSUE THREAD

**Issue by smithy1294** [ArcadeRenegade/SidebarDiagnostics#335]
**1. Is this a feature request?**
No this is an error

**2. Your Operating System**
Windows 10

**3. App Version**
Standalone Latest

**4. Any Relevant Settings**
Possibly CPU Temperature showing

**5. Steps to Reproduce**

Issue seems to be related to having a Kraken X63 installed with the NZXT CAM software open at the same time as the sidebar gives me the error in the attachment
![Screenshot_5](https://user-images.githubusercontent.com/15969750/101642889-6f491f80-3a2b-11eb-9819-46f0be2e4dbe.png)

**Comment by smithy1294** [comment]
Just tried the new version as well as i didn't notice that dropped and now no longer get this error but just get this
![image](https://user-images.githubusercontent.com/15969750/101645138-ec759400-3a2d-11eb-9bee-c0df42e6afc8.png)

**Comment by CZonin** [comment]
I've been running into both of these errors for awhile and haven't been able to use sidebar. I opened an issue awhile ago but it was closed: https://github.com/ArcadeRenegade/SidebarDiagnostics/issues/320

I also have a Kraken X63, but I don't have NZXT CAM running.

**Comment by ArcadeRenegade** [comment]
Please raise an issue with Libre Hardware Monitor

**Comment by CZonin** [comment]
Opened an issue with LHM here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/345

**Comment by CZonin** [comment]
@ArcadeRenegade Looks like the Kraken X63 issue was fixed in Libre Hardware Monitor today: [Link](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/ae60dcec1950068515b5a99bad75da854e5a4fec)

Do we need to wait for a new release of Libre Hardware Monitor for it to be updated in Sidebar Diagnostics?

**Comment by ArcadeRenegade** [comment]
I just need to do a new release.

**Comment by smithy1294** [comment]
Any chance of a new release at any point, still coming across this issue which makes the sidebar un-usuable

**Comment by ArcadeRenegade** [comment]
Hi, sorry I dropped the ball on this. I will do a release tonight or tomorrow.

**Comment by ArcadeRenegade** [comment]
Hey I just released a new version

**Comment by smithy1294** [comment]
Thanks for the update, might just be my end but im still having issues 
![Screenshot_3](https://user-images.githubusercontent.com/15969750/113897534-dea90300-97c2-11eb-8416-adc78cf387a1.png)

**Comment by attempted** [comment]
Also having the same issue after updating to the latest version.

**Comment by smithy1294** [comment]
Still getting problems with this, any advice?

**Comment by ntoskrnl4** [comment]
This is still an issue as I just found out building my new rig with a Kraken X63. Version 3.5.9, will work fine for a random amount of time (like 5 mins to an hour) before hitting this exception. Happens with and without* NZXT CAM installed. The reported error is the same as in this issue's original post and the above comments.

* aaand it died again lol

![crashlmao](https://user-images.githubusercontent.com/22060947/142947990-0b9e0efe-9d62-4432-9797-6f31cee5369b.png)
