### ISSUE TITLE
Staying in the background behind fullscreen video player

### ISSUE THREAD

**Issue by WitchDoctorAmI** [ArcadeRenegade/SidebarDiagnostics#67]
**1. Your Operating System**
Windows 10 Education
**2. App Version**
3.3.3
**3. Any Relevant Settings**

![2016-03-12 16_56_45-sidebar settings](https://cloud.githubusercontent.com/assets/17800347/13723924/210649be-e874-11e5-98f5-427cadd7516d.png)

**4. Steps to Reproduce**
I have the Sidebar on my second screen. I use my second screen to watch streams there.
When I go fullscreen on a videostream (in the example HTML5 Video with Chrome, same behaviour in Firefox with Flash (Twitch)) and click on my main screen on the desktop, the sidebar pops up in front of the video:

![2016-03-12 16_56_57-fussball_ bundesliga samstags-konferenz 26 spieltag _ sky go](https://cloud.githubusercontent.com/assets/17800347/13723926/27013586-e874-11e5-9509-e88c44fe6ee8.png)

Everytime this happens I have to click in the video so the sidebar gehts in the back again, at least until I click on the mainscreen again.

**Comment by ArcadeRenegade** [comment]
So the sidebar goes on top of the video if you click on your Windows desktop, correct?

**Comment by WitchDoctorAmI** [comment]
Yes, it is also reproducable.

**Comment by ArcadeRenegade** [comment]
I see. Unfortunately I am unable to reproduce. I am running a different version of Windows 10 though, Enterprise edition. Not sure why it is inconsistent.

**Comment by WitchDoctorAmI** [comment]
Now that you mention it - I had to upgrade from Win 10 Pro to Education due to a lost activation and Windows not accepting my Windows 8.1 key.
I think it did not happen beforehand.
Are there any information I can give you for an analysis of the problem? Can shoot a video of the problem too, if that helps.

**Comment by ArcadeRenegade** [comment]
Does it also go on top of non fullscreen windows in this situation?

I think this is related to the show desktop fix for when always on top setting is disabled. When you issue the show desktop command the sidebar becomes topmost. After, when another window becomes active it loses top most. Seems like it's triggering when you click the desktop even though it's not supposedly to.

**Comment by WitchDoctorAmI** [comment]
Hey, sorry for the wait.

Yeah, it also happens on non fullscreen windows, this is an example of it:

![2016-03-13 17_15_04-](https://cloud.githubusercontent.com/assets/17800347/13729857/4af22632-e93f-11e5-82be-7ba17ee86505.png)

Screenshot was taken across the two monitors, so to the right of the sidebar the right monitor begins.

**Comment by ArcadeRenegade** [comment]
I see. I'll try to think of a solution and get back to you.

**Comment by darniil** [comment]
I'm seeing this in Windows 8.1, too.  Program doesn't have to be fullscreen.  If I open a Windows Explorer window and move it so it's on top of the sidebar, the sidebar will go on top if I click on the desktop.  The sidebar will also go on top if I click on a link in the Start Menu.

**Comment by ArcadeRenegade** [comment]
I think the best I can do at the moment is have it pop up for a split second and then go back to the background. Would that be OK?

**Comment by darniil** [comment]
It's certainly better than nothing.  I say give it a shot.  :)

**Comment by WitchDoctorAmI** [comment]
Hey,
I just installed 3.3.4.

When I have something in front of the sidebar and click on the desktop, the sidebar is still on top. The only thing that changed now is that I can click in another windows on the other monitor - e.g. my browser - and the sidebar goes back into the background again. 
Better than before I guess, I can live with that until you find a full fix.

**Comment by darniil** [comment]
I got to wondering last night - could video drivers have any impact on this?  Or other software that tweaks aspects of Windows?  I realized I never mentioned that.

I have an NVIDIA GeForce GTX 760, with driver version 364.51.  I also have Stardock's Fences and Start8 installed.  What about you, WitchDoctor?

Can also confirm WD's analysis.  I'm running 3.3.4 now, and currently have a maximized browser on monitor 2, on top of the sidebar.  If I click on the desktop on monitor 1, the sidebar comes to the forefront.  However, if I click on another window open on monitor 1, or if I click on the start button, then the sidebar will go back behind the browser.

**Comment by WitchDoctorAmI** [comment]
I have a Geforce 770 installed, driver version is also 364.51. I use no tweaks like start 8 or anything like that though.

**Comment by ArcadeRenegade** [comment]
I haven't implemented the workaround yet. The change in 3.3.4 was a fix for a different bug I found while looking into a solution for you guys. I'll publish a release later tonight.

**Comment by ArcadeRenegade** [comment]
So I tested the fix I thought up for you guys but it breaks the "show desktop" fix. Having trouble finding a solution.

**Comment by darniil** [comment]
That's a bummer. I don't want you to end up breaking things for others.

I kinda wish I knew more about programming so I could help you out.  Unfortunately, that's not the case.  :(

I guess for now I'm okay with the way things currently are - that is, that the sidebar goes back behind the other programs once the desktop is no longer the "active window", as it were.

Thanks for your efforts.

**Comment by KarlOfDuty** [comment]
I can report that I have had the same issue and it was solved by clicking hide sidebar and then show sidebar again.

**Comment by darniil** [comment]
What version are you running, Karl?  Hiding and then showing did not resolve it for me.
